export const leavingCertificateSubjects = [
    "Accounting",
    "Agricultural Science",
    "Applied Maths",
    "Art",
    "Biology",
    "Business",
    "Chemistry",
    "Classical Studies",
    "Computer Science",
    "Construction Studies",
    "Design & Communication Graphics",
    "Economics",
    "Engineering",
    "English",
    "French",
    "Geography",
    "German",
    "History",
    "Home Economics",
    "Irish",
    "Italian",
    "Japanese",
    "LCVP (Link Modules)",
    "Mathematics",
    "Music",
    "Phys-Chem",
    "Physical Education",
    "Physics",
    "Politics and Society",
    "Religious Education",
    "Spanish",
    "Technology"
  ];
  
  export const juniorCertificateSubjects = [
    "Applied Technology",
    "Business Studies",
    "Classics",
    "CSPE",
    "Engineering",
    "English",
    "French",
    "Geography",
    "German",
    "Graphics",
    "History",
    "Home Economics",
    "Irish T2",
    "Italian",
    "Mathematics",
    "Music",
    "Religious Education",
    "Science",
    "Spanish",
    "SPHE",
    "Wood Technology"
  ];
  